# Generated by Django 4.2 on 2023-04-07 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conteudo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conteudo",
            name="likes",
            field=models.ManyToManyField(
                related_name="like_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
