# Generated by Django 4.2 on 2023-04-09 19:36

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ("conteudo", "0002_conteudo_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="conteudo",
            name="url",
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
